width = float(input('ความกว้าง = '))
long = float(input('ความยาว = '))
high = float(input('ความสูง = '))
print('.................................')
area = float(((width * long * 2)+(width * high * 2)+(long *high * 2)))/5
print('.................................')
print('กล่องสีเหลี่ยมผืนผ้ามีความกว้าง',width,'ยาว',long,'สูง',high,'ต้องใช้สีทั้งหมด',round(area),'แกลอน')
print("กล่องสีเหลี่ยมผืนผ้ามีความกว้าง"+" "+ str(width)+" "+ "ยาว"+" "+ str(long)+" "+ "สูง"+" " +str(high)+" " +"ต้องใช้สีทั้งหมด"+" "+ str(round(area))+" "+ "แกลอน")
print(f"กล่องสีเหลี่ยมผืนผ้ามีความกว้าง {width} ยาว {long} สูง {high} ต้องใช้สีทั้งหมด {round(area)} แกลอน ")
print("กล่องสีเหลี่ยมผืนผ้ามีความกว้าง {} ยาว {} สูง {} ต้องใช้สีทั้งหมด {} แกลอน ".format(width,long,high,round(area)))